name: Greet everyone
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Dieg"
        id: hello
      - name: Echo the greetings time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
