name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'build dock')"

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file ./src/frontend-service/Dockerfile --tag my-image-name:$(date +%s)
